# Generated by Django 2.2.4 on 2019-09-16 19:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190828_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrule',
            name='score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
    ]
